Repository Nexters/invi, pull requests merged in 2024-08, with the labels that each got.

#20 fix: component ui badge 사용
  src/components/editor/elements/text.tsx
Labels: fix

#21 chore: tasks.json을 추가합니다.
  .vscode/tasks.json
  package.json
Labels: chore

#19 INV-68 주소 블럭 컴포넌트
  src/components/editor/elements/container.tsx
  src/components/editor/elements/map-placeholder.tsx
  src/components/editor/elements/map-share.tsx
  src/components/editor/elements/recursive.tsx
  src/components/editor/sidebar-components-tab.tsx
  src/components/editor/sidebar-settings-tab.tsx
  src/components/editor/type.ts
Labels: feat

#23 fix: rename from playground to pg
  src/app/(auth)/sign-in/google/callback/route.ts
  src/app/(auth)/sign-in/kakao/callback/route.ts
  src/app/(auth)/sign-in/naver/callback/route.ts
  src/app/(auth)/sign-out/actions.ts
  src/app/(auth)/sign-out/route.ts
  src/app/(playground)/pg/invitation-response/[responseId]/page.tsx
  src/app/(playground)/pg/invitation-response/invitation-response-list.tsx
  src/app/(playground)/pg/test/[testId]/page.tsx
  src/app/(playground)/pg/test/test-list.tsx
  src/lib/db/schema/test.query.ts
Labels: fix

#24 inv-72 NCP 오브젝트 스토리지 파일 업로드 서버 액션 구현
  .env.template
  bun.lockb
  package.json
  src/lib/env.ts
  src/lib/storage/object_storage_uploader.ts
Labels: chore, feat

#26 refactor: layout
  src/app/(main)/layout.tsx
  src/app/(playground)/pg/error/page.tsx
  src/app/(playground)/pg/layout.tsx
  src/app/(ut)/ut/layout.tsx
  src/app/(ut)/ut/style.css
  src/app/error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
Labels: refactor

#27 inv-77 사이드바 > 선택된 엘리먼트 설정 세팅
  src/components/editor/action.ts
  src/components/editor/constant.ts
  src/components/editor/index.tsx
  src/components/editor/main.tsx
  src/components/editor/sidebar-element-settings-tab.tsx
  src/components/editor/sidebar-elements-tab.tsx
  src/components/editor/sidebar-settings-tab.tsx
  src/components/editor/sidebar.tsx
  src/components/editor/type.ts
  src/components/editor/util.ts
Labels: feat

#28 inv-105 블럭 > 보조 레이어 > 마크업
  src/components/editor/elements/container.tsx
  src/components/editor/elements/element-wrapper.tsx
  src/components/editor/elements/map-share.tsx
  src/components/editor/elements/recursive.tsx
  src/components/editor/elements/text.tsx
  src/components/editor/elements/two-columns.tsx
Labels: feat

#30 inv-99 네비게이션 > dropdown 마크업
  src/components/editor/navigation.tsx
  src/components/editor/sidebar.tsx
  src/components/providers.tsx
  src/components/ui/tooltip-simple.tsx
Labels: feat

#31 inv-95 네비게이션 > 제목 입력 > 마크업
  bun.lockb
  package.json
  src/components/editor/navigation.tsx
  src/components/editor/title-input.tsx
Labels: chore, feat

#32 refactor: placeholder
  src/components/editor/elements/container-placeholder.tsx
  src/components/editor/elements/map-placeholder.tsx
  src/components/editor/elements/placeholder.tsx
  src/components/editor/elements/text-placeholder.tsx
  src/components/editor/elements/two-columns-placeholder.tsx
  src/components/editor/placeholders.tsx
  src/components/editor/sidebar-elements-tab.tsx
Labels: refactor

#33 inv-83 엘리먼트 > 컨테이너 > 레이아웃 설정 > 마크업 구현
  bun.lockb
  package.json
  src/app/globals.css
  src/components/editor/navigation.tsx
  src/components/editor/sidebar-element-settings-tab.tsx
  src/components/editor/sidebar-element-settings-tab/advance-setting.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-element-settings-tab/layout-setting.tsx
  src/components/editor/sidebar-element-settings-tab/map-setting.tsx
  src/components/editor/ui/input.tsx
  src/components/ui/icons.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/components/ui/tooltip-simple.tsx
Labels: chore, feat

#34 inv-134 기본적인 서비스 구조 잡기
  next.config.mjs
  src/app/(auth)/sign-in/google/callback/route.ts
  src/app/(auth)/sign-in/kakao/callback/route.ts
  src/app/(auth)/sign-in/naver/callback/route.ts
  src/app/(auth)/sign-out/actions.ts
  src/app/(auth)/sign-out/route.ts
  src/app/(main)/dashboard/page.tsx
  src/app/(main)/page.tsx
  src/app/(main)/sign-in/page.tsx
  src/app/(playground)/pg/layout.tsx
  src/app/layout.tsx
  src/components/profile-dropdown.tsx
  src/components/providers.tsx
  src/lib/auth/utils.ts
Labels: feat

#40 feature/inv-78 엘리먼트 > 컨테이너 > 레이아웃 설정
  src/components/editor/constant.ts
  src/components/editor/sidebar-element-settings-tab/layout-setting.tsx
  src/components/editor/ui/align-input-box.tsx
  src/components/editor/ui/flex-toggle-group.tsx
Labels: feat

#25 INV-50 와일드카드 서브도메인 rewrite 라우팅 처리
  next.config.mjs
  src/app/(playground)/pg/[subdomain]/page.tsx
  src/middleware.ts
Labels: feat

#37 Feature/inv-120 커스텀 url 기반 중복 여부 조회 로직 구현
  src/lib/db/schema/invitations.query.ts
Labels: feat

#38 Feature/inv 122 템플릿 CRUD 메서드 구현
  src/lib/db/schema/templates.query.ts
Labels: feat

#39 Feature/inv-108 회원 탈퇴 및 로그아웃 구현
  src/lib/db/schema/users.query.ts
Labels: feat

#29 [inv-73] feat: invitation, template schema 정의
  src/lib/db/migrations/0005_fine_argent.sql
  src/lib/db/migrations/0006_condemned_randall.sql
  src/lib/db/migrations/0007_parallel_meggan.sql
  src/lib/db/migrations/meta/0005_snapshot.json
  src/lib/db/migrations/meta/0006_snapshot.json
  src/lib/db/migrations/meta/0007_snapshot.json
  src/lib/db/migrations/meta/_journal.json
  src/lib/db/schema/invitation_response.ts
  src/lib/db/schema/invitations.query.ts
  src/lib/db/schema/invitations.ts
  src/lib/db/schema/templates.query.ts
  src/lib/db/schema/templates.ts
Labels: feat, db

#43 fix: localhost이 서브도메인으로 인식되지 않도록
  src/middleware.ts
Labels: fix

#41 inv-79, inv-80, inv-84, inv-85 엘리먼트 > 컨테이너 > 설정
  src/components/editor/constant.ts
  src/components/editor/elements/container.tsx
  src/components/editor/sidebar-element-settings-tab/advance-setting.tsx
  src/components/editor/sidebar-element-settings-tab/background-setting.tsx
  src/components/editor/sidebar-element-settings-tab/border-setting.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-element-settings-tab/layout-setting.tsx
  src/components/editor/sidebar-element-settings-tab/map-setting.tsx
  src/components/editor/sidebar-element-settings-tab/text-setting.tsx
  src/components/editor/sidebar-elements-tab.tsx
  src/components/editor/ui/input.tsx
  src/components/editor/ui/text-align-toggle-group.tsx
Labels: chore, feat

#42 inv-106 블럭 > 보조 레이어 > 동작 연동
  src/components/editor/action.ts
  src/components/editor/elements/container.tsx
  src/components/editor/elements/element-helper.tsx
  src/components/editor/elements/element-wrapper.tsx
  src/components/editor/main.tsx
Labels: feat

#45 feat: editor 설정
  src/app/(playground)/pg/editor/page.tsx
  src/app/(playground)/pg/page.tsx
  src/components/editor/action.ts
  src/components/editor/constant.ts
  src/components/editor/elements/element-helper.tsx
  src/components/editor/elements/text.tsx
  src/components/editor/index.tsx
  src/components/editor/main.tsx
  src/components/editor/navigation.tsx
  src/components/editor/provider.tsx
  src/components/editor/title-input.tsx
  src/components/editor/type.ts
Labels: feat

#44 [inv-114] feat: 초대장 생성 API
  src/lib/db/schema/invitations.query.ts
Labels: feat

#46 [inv-115] feat: 초대장 단건/리스트 조회 API
  src/lib/db/schema/invitations.query.ts
  src/lib/db/schema/invitations.ts
  src/lib/db/schema/templates.query.ts
Labels: feat

#47 fix: 선택된 엘리먼트의 상태가 변경되지 않는 현상
  src/components/editor/action.ts
  src/components/editor/elements/element-helper.tsx
  src/components/editor/sidebar-element-settings-tab/background-setting.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-element-settings-tab/layout-setting.tsx
  src/components/editor/sidebar-element-settings-tab/text-setting.tsx
  src/components/editor/ui/input.tsx
Labels: fix

#49 [inv-117] feat: 초대장 삭제 API
  src/lib/db/schema/invitations.query.ts
  src/lib/db/schema/templates.query.ts
Labels: feat

#50 INV-128: 대시보드 > 초대장 > 리스트 연동
  src/app/(main)/dashboard/page.tsx
  src/app/(main)/i/[subdomain]/edit/page.tsx
  src/app/(playground)/pg/[subdomain]/page.tsx
Labels: feat

#22 inv-67 카카오맵 컴포넌트 구현
  src/app/(playground)/pg/editor/layout.tsx
  src/components/editor/action.ts
  src/components/editor/constant.ts
  src/components/editor/elements/container.tsx
  src/components/editor/elements/element-helper.tsx
  src/components/editor/elements/kakao-map-context.tsx
  src/components/editor/elements/kakao-map-element.tsx
  src/components/editor/elements/kakao-map.tsx
  src/components/editor/elements/map-share.tsx
  src/components/editor/elements/recursive.tsx
  src/components/editor/placeholders.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-element-settings-tab/kakao-map-setting.tsx
  src/components/editor/sidebar-elements-tab.tsx
  src/components/editor/sidebar-settings-tab.tsx
  src/components/editor/type.ts
Labels: feat

#51 inv-88 inv-90 엘리먼트 > 이미지
  .eslintrc.json
  bun.lockb
  package.json
  src/components/editor/elements/container.tsx
  src/components/editor/elements/image-element.tsx
  src/components/editor/elements/recursive.tsx
  src/components/editor/placeholders.tsx
  src/components/editor/sidebar-element-settings-tab/image-setting.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-elements-tab.tsx
  src/components/editor/ui/image-dropzone.tsx
Labels: chore, feat

#52 fix: invitation schema
  src/lib/db/schema/invitations.query.ts
  src/lib/db/schema/invitations.ts
Labels: fix

#54 refactor: cleanup
  src/components/editor/elements/container.tsx
  src/components/editor/elements/kakao-map-element.tsx
  src/components/editor/placeholders.tsx
  src/components/editor/sidebar-elements-tab.tsx
Labels: refactor

#53 inv-92 inv-94 엘리먼트 > 여백
  src/components/editor/elements/blank-element.tsx
  src/components/editor/elements/container.tsx
  src/components/editor/elements/recursive.tsx
  src/components/editor/placeholders.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-elements-tab.tsx
  src/components/editor/type.ts
Labels: feat

#59 inv-76 사이드바 > 사이트 설정 > 마크업
  src/components/editor/action.ts
  src/components/editor/constant.ts
  src/components/editor/navigation.tsx
  src/components/editor/provider.tsx
  src/components/editor/sidebar-settings-tab.tsx
  src/components/editor/title-input.tsx
  src/components/editor/type.ts
  src/components/editor/ui/input.tsx
Labels: feat

#62 feat: 에디터 body 설정
  src/app/(playground)/pg/editor/page.tsx
  src/components/editor/action.ts
  src/components/editor/constant.ts
  src/components/editor/elements/container.tsx
  src/components/editor/elements/element-helper.tsx
  src/components/editor/elements/element-wrapper.tsx
  src/components/editor/elements/logo-banner-element.tsx
  src/components/editor/elements/recursive.tsx
  src/components/editor/main.tsx
  src/components/editor/placeholders.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-element-settings-tab/logo-banner-setting.tsx
  src/components/editor/sidebar-elements-tab.tsx
  src/components/editor/type.ts
  src/components/editor/util.ts
  src/components/ui/icons.tsx
Labels: feat

#63 fix: 보조 레이어가 스크롤을 안따라가는 현상
  bun.lockb
  package.json
  src/app/globals.css
  src/components/editor/action.ts
  src/components/editor/elements/container.tsx
  src/components/editor/elements/element-helper.tsx
  src/components/editor/elements/image-element.tsx
  src/components/editor/index.tsx
  src/components/editor/main.tsx
  src/components/ui/scroll-area.tsx
Labels: chore, fix

#64 inv-126 : 타이틀, 내용 업데이트 쿼리
  src/app/(main)/dashboard/page.tsx
  src/app/(main)/i/[subdomain]/edit/page.tsx
  src/app/(main)/i/layout.tsx
  src/components/editor/navigation.tsx
  src/components/editor/title-input.tsx
  src/lib/db/schema/invitations.query.ts
  src/lib/db/schema/invitations.ts
Labels: feat

#65 INV-89: cdn 연동
  bun.lockb
  package.json
  src/app/api/uploadImage/route.ts
  src/components/editor/sidebar-element-settings-tab/image-setting.tsx
  src/components/editor/sidebar-settings-tab.tsx
  src/components/editor/ui/image-dropzone.tsx
  src/lib/storage/object_storage_uploader.ts
Labels: chore, feat

#66 feat: NCP CDN 연동
  src/app/api/uploadImage/route.ts
  src/components/editor/elements/image-element.tsx
  src/components/editor/sidebar-element-settings-tab/image-setting.tsx
  src/components/editor/sidebar-settings-tab.tsx
  src/components/editor/ui/image-dropzone.tsx
  src/components/editor/ui/input.tsx
  src/components/ui/icons.tsx
  src/lib/image.ts
  src/lib/thumbnail.ts
Labels: feat

#67 feat: 템플릿 & 초대장 연동
  bun.lockb
  package.json
  src/app/(main)/dashboard/invitation-item.tsx
  src/app/(main)/dashboard/page.tsx
  src/app/(main)/dashboard/template-item.tsx
  src/app/(main)/i/[subdomain]/edit/page.tsx
  src/components/profile-dropdown.tsx
  src/components/ui/icons.tsx
  src/lib/db/migrations/0000_flippant_darkhawk.sql
  src/lib/db/migrations/0000_tranquil_sasquatch.sql
  src/lib/db/migrations/0001_far_archangel.sql
  src/lib/db/migrations/0001_watery_lord_tyger.sql
  src/lib/db/migrations/0002_zippy_stature.sql
  src/lib/db/migrations/0003_peaceful_white_tiger.sql
  src/lib/db/migrations/0004_lying_swordsman.sql
  src/lib/db/migrations/0005_fine_argent.sql
  src/lib/db/migrations/0006_condemned_randall.sql
  src/lib/db/migrations/0007_parallel_meggan.sql
  src/lib/db/migrations/meta/0000_snapshot.json
  src/lib/db/migrations/meta/0001_snapshot.json
  src/lib/db/migrations/meta/0002_snapshot.json
  src/lib/db/migrations/meta/0003_snapshot.json
  src/lib/db/migrations/meta/0004_snapshot.json
  src/lib/db/migrations/meta/0005_snapshot.json
  src/lib/db/migrations/meta/0006_snapshot.json
  src/lib/db/migrations/meta/0007_snapshot.json
  src/lib/db/migrations/meta/_journal.json
  src/lib/db/migrations/relations.ts
  src/lib/db/migrations/schema.ts
  src/lib/db/schema/templates.query.ts
  src/lib/db/schema/templates.ts
Labels: chore, feat

#68 refactor: map find > navigation
  src/components/editor/elements/container.tsx
  src/components/editor/elements/kakao-map.tsx
  src/components/editor/elements/navigation-element.tsx
  src/components/editor/elements/recursive.tsx
  src/components/editor/placeholders.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-element-settings-tab/map-setting.tsx
  src/components/editor/sidebar-elements-tab.tsx
  src/components/editor/type.ts
Labels: refactor

#69 feat: 초대장 페이지
  src/app/(main)/i/[subdomain]/edit/page.tsx
  src/app/(main)/i/[subdomain]/page.tsx
  src/app/layout.tsx
  src/components/editor/elements/image-element.tsx
  src/components/editor/elements/navigation-element.tsx
  src/components/editor/navigation.tsx
  src/components/editor/provider.tsx
  src/components/editor/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar-settings-tab.tsx
  src/middleware.ts
Labels: feat

#70 refactor: editor data schema
  src/app/(main)/i/[subdomain]/page.tsx
  src/app/(playground)/pg/editor/page.tsx
  src/components/editor/action.ts
  src/components/editor/constant.ts
  src/components/editor/elements/recursive.tsx
  src/components/editor/main.tsx
  src/components/editor/sidebar/index.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/background-setting.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/border-setting.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/image-setting.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/index.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/kakao-map-setting.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/layout-setting.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/logo-banner-setting.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/map-setting.tsx
  src/components/editor/sidebar/sidebar-element-settings-tab/text-setting.tsx
  src/components/editor/sidebar/sidebar-elements-tab.tsx
  src/components/editor/sidebar/sidebar-settings-tab.tsx
  src/components/editor/type.ts
Labels: refactor

#71 draft: invi response
  bun.lockb
  package.json
  src/app/(main)/i/[subdomain]/page.tsx
  src/components/editor/constant.ts
  src/components/editor/fab/index.tsx
  src/components/editor/fab/invitation-response-fab.tsx
  src/components/editor/main.tsx
  src/components/editor/provider.tsx
  src/components/editor/sidebar/index.tsx
  src/components/editor/sidebar/sidebar-invitation-response-tab.tsx
  src/components/editor/type.ts
  src/components/ui/drawer.tsx
Labels: chore, feat

#77 feat: favicon
  src/app/favicon.ico
  src/app/icon.png
Labels: feat

#79 feat: OG 이미지 설정
  src/app/(main)/dashboard/template-item.tsx
  src/app/(main)/i/[subdomain]/page.tsx
  src/app/layout.tsx
  src/components/editor/sidebar/sidebar-settings-tab.tsx
  src/lib/db/schema/invitations.query.ts
Labels: feat

#80 feat: 로딩
  bun.lockb
  package.json
  src/app/(main)/dashboard/template-item.tsx
  src/app/(main)/loading.tsx
  src/components/core/in-view.tsx
  src/components/core/text-effect.tsx
  src/components/editor/navigation.tsx
  src/components/editor/sidebar/sidebar-settings-tab.tsx
  src/components/gloabl-loading.tsx
  src/components/providers.tsx
  tailwind.config.ts
Labels: chore, feat

#81 feat: 회원탈퇴 고도화
  src/app/(auth)/sign-out/actions.ts
  src/components/profile-dropdown.tsx
  src/lib/db/migrations/0003_flippant_the_professor.sql
  src/lib/db/migrations/meta/0003_snapshot.json
  src/lib/db/migrations/meta/_journal.json
  src/lib/db/migrations/schema.ts
  src/lib/db/schema/auth.ts
  src/lib/db/schema/invitation_response.ts
  src/lib/db/schema/invitations.ts
  src/lib/db/schema/users.query.ts
Labels: feat

#84 feat: sort template
  bun.lockb
  src/app/(main)/dashboard/page.tsx
Labels: chore, feat

#85 feat: 초대장 복제하기 기능
  src/components/editor/navigation.tsx
  src/components/gloabl-loading.tsx
Labels: feat

#86 refactor: accordion element innerContainer
  src/components/editor/elements/accordion-element.tsx
  src/components/editor/elements/container.tsx
  src/components/editor/type.ts
Labels: refactor

#91 feat: editor tooltip
  src/components/editor/action.ts
  src/components/editor/constant.ts
  src/components/editor/navigation.tsx
  src/components/editor/sidebar/index.tsx
  src/components/ui/tooltip-simple.tsx
Labels: feat

#90 refactor: 초대장 SEO 설명 연동
  src/app/(main)/i/[subdomain]/page.tsx
  src/app/layout.tsx
  src/components/editor/sidebar/sidebar-settings-tab.tsx
  src/lib/db/migrations/0004_tranquil_pandemic.sql
  src/lib/db/migrations/meta/0004_snapshot.json
  src/lib/db/migrations/meta/_journal.json
  src/lib/db/schema/invitations.query.ts
  src/lib/db/schema/invitations.ts
Labels: refactor

#83 inv-151: 참여여부 바텀시트
  src/app/(main)/i/[subdomain]/page.tsx
  src/app/(playground)/pg/bottom-sheet/_components/bottom-sheet/index.tsx
  src/components/editor/action.ts
  src/components/editor/fab/image-radio/container.tsx
  src/components/editor/fab/image-radio/index.tsx
  src/components/editor/fab/image-radio/option.tsx
  src/components/editor/fab/index.tsx
  src/components/editor/fab/invitation-response-fab.tsx
  src/components/editor/main.tsx
  src/components/editor/sidebar/sidebar-invitation-response-tab.tsx
Labels: chore, feat

#94 fix: editor history
  src/components/editor/action.ts
  src/components/editor/provider.tsx
Labels: fix

#93 feat: darkmode
  src/app/(main)/dashboard/page.tsx
  src/components/editor/navigation.tsx
  src/components/profile-dropdown.tsx
  src/components/providers.tsx
  src/components/theme-dropdown.tsx
Labels: feat

#96 feat: 🐝 drag and drop
  src/components/editor/action.ts
  src/components/editor/constant.ts
  src/components/editor/elements/container.tsx
  src/components/editor/elements/element-helper.tsx
  src/components/editor/elements/element-wrapper.tsx
  src/components/editor/elements/image-element.tsx
  src/components/editor/placeholders.tsx
  src/components/editor/type.ts
  src/components/editor/util.ts
Labels: feat

#95 fix: invitation_id 기반 get
  src/lib/db/schema/invitation_response.query.ts
Labels: fix

#92 inv-153: 참여여부 투표 / 에디터에서 투표 결과 확인 테이블
  src/app/(main)/i/[subdomain]/page.tsx
  src/app/(playground)/pg/bottom-sheet/_components/bottom-sheet/index.tsx
  src/app/(playground)/pg/invitation-response/[responseId]/invitation-response-info.tsx
  src/assets/attendance/attendance-true-default.svg
  src/components/editor/fab/invitation-response-fab.tsx
  src/components/editor/main.tsx
  src/components/editor/sidebar/sidebar-invitation-response-tab.tsx
  src/components/ui/table.tsx
  src/lib/db/schema/invitation_response.query.ts
  src/lib/utils.ts
Labels: chore, feat
